2017-04-11 09:27:17.365 - eddnlistener - WARNING - eddnlistener.main: Disconnect from tcp://eddn-relay.elite-markets.net:9500
Traceback (most recent call last):
  File "./eddnlistener.py", line 92, in main
    __message   = __subscriber.recv()
  File "zmq/backend/cython/socket.pyx", line 631, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5772)
  File "zmq/backend/cython/socket.pyx", line 665, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5572)
  File "zmq/backend/cython/socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1725)
  File "zmq/backend/cython/checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6112)
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eddnlistener.py", line 202, in <module>
    main()
  File "./eddnlistener.py", line 135, in main
    time.sleep(5)
NameError: name 'time' is not defined
You have mail in /home/users/athan/Maildir
athan@tuesday:/mnt/tuesday/data0/edda/edda.git/eddn-listener;
10:27:17 0$

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Wed 10 May 12:59:36 BST 2017
2017-05-07 02:10:38.953 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted ED-IBE (API) (0.6.4)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./eddnlistener.py", line 174, in <module>
    main()
  File "./eddnlistener.py", line 142, in main
    __db.insertMessage(__eddn_message.json, __message_blacklisted, __message_valid, __message_schema_is_test)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 29, in insertMessage
    session.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) terminating connection due to administrator command
SSL connection has been closed unexpectedly
 'INSERT INTO messages (message_raw, message, blacklisted, message_valid, schema_test) VALUES (%(message_raw)s, %(message)s, %(blacklisted)s, %(message_valid)s, %(schema_test)s) RETURNING messages.id' {'message_raw': '{"$schemaRef": "http://schemas.elite-markets.net/eddn/journal/1", "header": {"softwareVersion": "7.0.0.0", "uploaderID": "Felina Hawk", "gatewayTimestamp": "2017-05-07T02:11:39.990741Z", "softwareName": "EDDiscovery"}, "message": {"timestamp": "2017-05-07T02:11:39Z", "Age_MY": 3102, "StarType": "N", "RotationPeriod": 1.844558, "StarPos": [-14434.125, -10.0, 29932.75], "event": "Scan", "SurfaceTemperature": 5471000.0, "StellarMass": 0.742188, "StarSystem": "Eowyg Brai YS-U d2-70", "Radius": 11082.03125, "BodyName": "Eowyg Brai YS-U d2-70", "AbsoluteMagnitude": 5.134415, "DistanceFromArrivalLS": 0.0}}', 'message_valid': True, 'message': '{"$schemaRef": "http://schemas.elite-markets.net/eddn/journal/1", "header": {"softwareVersion": "7.0.0.0", "uploaderID": "Felina Hawk", "gatewayTimestamp": "2017-05-07T02:11:39.990741Z", "softwareName": "EDDiscovery"}, "message": {"timestamp": "2017-05-07T02:11:39Z", "Age_MY": 3102, "StarType": "N", "RotationPeriod": 1.844558, "StarPos": [-14434.125, -10.0, 29932.75], "event": "Scan", "SurfaceTemperature": 5471000.0, "StellarMass": 0.742188, "StarSystem": "Eowyg Brai YS-U d2-70", "Radius": 11082.03125, "BodyName": "Eowyg Brai YS-U d2-70", "AbsoluteMagnitude": 5.134415, "DistanceFromArrivalLS": 0.0}}', 'schema_test': False, 'blacklisted': False}
You have mail in /home/users/athan/Maildir
athan@tuesday:/mnt/tuesday/data0/edda/edda.git/eddn-listener;
03:11:45 1$
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Startup is very slow when looking to backfill EDDN messages and trying
to find the latest message of a given type, i.e.:

2017-05-10 13:17:56 BST [26980-2] eddnlistener@eddn STATEMENT:  SELECT messages.message AS messages_message 
        FROM messages 
        WHERE (messages.message ->> '$schemaRef') LIKE '%blackmarket%' AND (messages.message #> '{header, gatewayTimestamp}') IS NOT NULL ORDER BY messages.message #> '{header, gatewayTimestamp}' DESC 
         LIMIT 1

is very slow.  It comes from this in eddn/database/database.py:

  def latestMessageTimestamp(self, archiveType):
    session = self.Session()
    gatewayTimestamp = Message.message[("header", "gatewayTimestamp")]
    schema = Message.message[("$schemaRef")].astext
    results = session.query(Message.message).filter(schema.like("%"+archiveType+"%")).filter(gatewayTimestamp != None).order_by(desc(gatewayTimestamp)).limit(1)
    for r in results:
      return r.message['header']['gatewayTimestamp']
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Wed 26 Jul 21:39:38 BST 2017
2017-07-26 19:50:24.986 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted EDDiscovery (8.1.3.0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: invalid page in block 130948 of relation base/16394/16455


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 35, in insertMessage
    session.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) invalid page in block 130948 of relation base/16394/16455
 [SQL: 'INSERT INTO messages (message, message_search, blacklisted, message_valid, schema_test, schemaref, gatewaytimestamp) VALUES (%(message)s, %(message_search)s, %(blacklisted)s, %(message_valid)s, %(schema_test)s, %(schemaref)s, %(gatewaytimestamp)s) RETURNING messages.id'] [parameters: {'message': '{"header": {"uploaderID": "BeanGTR", "softwareVersion": "2.3.0", "gatewayTimestamp": "2017-07-26T19:50:15.321473Z", "softwareName": "EDDI"}, "message": {"PlanetClass": "High metal content body", "SemiMajorAxis": 1069009797120.0, "StarPos": [-206.78125, 27.1875, -92.25], "event": "Scan", "timestamp": "2017-07-26T19:50:34Z", "DistanceFromArrivalLS": 3591.29541, "Radius": 7715584.5, "OrbitalPeriod": 526916160.0, "MassEM": 2.283549, "Eccentricity": 0.008741, "Periapsis": 150.545395, "RotationPeriod": 118229.296875, "StarSystem": "Col 285 Sector KS-T d3-68", "AxialTilt": -2.86825, "SurfaceGravity": 15.289104, "OrbitalInclination": -0.011449, "BodyName": "Col 285 Sector KS-T d3-68 A 5"}, "$schemaRef": "http://schemas.elite-markets.net/eddn/journal/1"}', 'schema_test': False, 'schemaref': 'journal', 'blacklisted': False, 'message_search': 'null', 'gatewaytimestamp': '2017-07-26T19:50:15.321473Z', 'message_valid': True}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eddnlistener.py", line 175, in <module>
    main()
  File "./eddnlistener.py", line 142, in main
    __db.insertMessage(__eddn_message.json, __eddn_message.schemaref, __eddn_message.gatewaytimestamp,__message_blacklisted, __message_valid, __message_schema_is_test)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 37, in insertMessage
    except sqlalchemy.exc.OperationalError as ex:
NameError: name 'sqlalchemy' is not defined
athan@tuesday:/mnt/tuesday/data0/edda/edda.git/eddn-listener;
20:50:33 0$
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Wed  9 Aug 12:53:27 BST 2017
2017-08-09 11:52:44.193 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted ED-IBE (API) (0.6.6)
2017-08-09 11:52:52.924 - eddnlistener - WARNING - utils.validateEDDNMessage: ('$schemaRef did not match regex: https://eddn.edcd.io/schemas/journal/1',)
Traceback (most recent call last):
  File "./eddnlistener.py", line 175, in <module>
    main()
  File "./eddnlistener.py", line 111, in main
    (__eddn_message, __message_valid, __message_blacklisted, __message_schema_is_test) = validateEDDNMessage(__message, __config, __logger)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/utils.py", line 28, in validateEDDNMessage
    __message_schema_is_test = __eddn_message.schema_is_test
AttributeError: 'message' object has no attribute 'schema_is_test'

FIXED: __eddn_message.schema_is_test was only being initialised AFTER
the "known schema" regex test, which was against the old URLs.  Moved
the initialisation to False earlier as well as updating the schema URL
regex.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Thu 10 Aug 18:35:38 BST 2017
2017-08-10 17:29:10.862 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted EDDiscovery (8.1.4.0)
Traceback (most recent call last):
  File "./eddnlistener.py", line 175, in <module>
    main()
  File "./eddnlistener.py", line 111, in main
    (__eddn_message, __message_valid, __message_blacklisted, __message_schema_is_test) = validateEDDNMessage(__message, __config, __logger)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/utils.py", line 19, in validateEDDNMessage
    __eddn_message.validate()
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/message/message.py", line 84, in validate
    validate(self.json, schemainfo["schema"])
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: 'Location' is not one of ['Docked', 'FSDJump', 'Scan']

Failed validating 'enum' in schema['properties']['message']['properties']['event']:
    {'enum': ['Docked', 'FSDJump', 'Scan']}

On instance['message']['event']:
    'Location'
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Fri 11 Aug 08:12:29 BST 2017
Due to psql upgrade:
2017-08-10 17:56:48.180 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted EDDiscovery (8.1.4.0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 35, in insertMessage
    session.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 [SQL: 'INSERT INTO messages (message, message_search, blacklisted, message_valid, schema_test, schemaref, gatewaytimestamp) VALUES (%(message)s, %(message_search)s, %(blacklisted)s, %(message_valid)s, %(schema_test)s, %(schemaref)s, %(gatewaytimestamp)s) RETURNING messages.id'] [parameters: {'message_valid': True, 'blacklisted': False, 'message': '{"$schemaRef": "https://eddn.edcd.io/schemas/journal/1", "header": {"softwareName": "E:D Market Connector [Windows]", "gatewayTimestamp": "2017-08-11T07:08:10.384830Z", "softwareVersion": "2.3.6.0", "uploaderID": "Gameboy13579"}, "message": {"StarPos": [-83.531, -114.813, -260.031], "StarType": "K", "AbsoluteMagnitude": 7.098755, "StarSystem": "Pleiades Sector QT-R c4-12", "SurfaceTemperature": 3856.0, "timestamp": "2017-08-11T07:08:43Z", "Age_MY": 12110, "OrbitalPeriod": 7582140416.0, "BodyName": "Pleiades Sector QT-R c4-12 A", "SemiMajorAxis": 1361966006272.0, "event": "Scan", "Radius": 549472128.0, "StellarMass": 0.597656, "Eccentricity": 0.050743, "DistanceFromArrivalLS": 0.0, "RotationPeriod": 269101.03125, "OrbitalInclination": 55.624729, "AxialTilt": 0.0, "Periapsis": 184.194183}}', 'schemaref': 'journal', 'message_search': 'null', 'schema_test': False, 'gatewaytimestamp': '2017-08-11T07:08:10.384830Z'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eddnlistener.py", line 175, in <module>
    main()
  File "./eddnlistener.py", line 142, in main
    __db.insertMessage(__eddn_message.json, __eddn_message.schemaref, __eddn_message.gatewaytimestamp,__message_blacklisted, __message_valid, __message_schema_is_test)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 37, in insertMessage
    except sqlalchemy.exc.OperationalError as ex:
NameError: name 'sqlalchemy' is not defined
You have new mail in /home/users/athan/Maildir
athan@tuesday:/mnt/tuesday/data0/edda/edda.git/eddn-listener;
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
2017-09-10 01:34:30.417 - eddnlistener - INFO - utils.validateEDDNMessage: Blacklisted EDDiscovery (8.1.4.0)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: invalid page in block 15209 of relation base/16394/16455


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 35, in insertMessage
    session.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) invalid page in block 15209 of relation base/16394/16455
 [SQL: 'INSERT INTO messages (message, message_search, blacklisted, message_valid, schema_test, schemaref, gatewaytimestamp) VALUES (%(message)s, %(message_search)s, %(blacklisted)s, %(message_valid)s, %(schema_test)s, %(schemaref)s, %(gatewaytimestamp)s) RETURNING messages.id'] [parameters: {'schemaref': 'commodity', 'gatewaytimestamp': '2017-09-10T12:43:19.369090Z', 'blacklisted': False, 'schema_test': False, 'message_search': 'null', 'message_valid': True, 'message': '{"$schemaRef": "https://eddn.edcd.io/schemas/commodity/3", "header": {"softwareVersion": "2.4.2.0", "gatewayTimestamp": "2017-09-10T12:43:19.369090Z", "uploaderID": "Jake Valent", "softwareName": "E:D Market Connector [Windows]"}, "message": {"commodities": [{"meanPrice": 110, "demand": 1, "stockBracket": 2, "sellPrice": 86, "name": "Hydrogen Fuel", "stock": 132276, "buyPrice": 90, "demandBracket": 0}, {"meanPrice": 917, "demand": 588783, "stockBracket": 0, "sellPrice": 900, "name": "Hydrogen Peroxide", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 263, "demand": 313110, "stockBracket": 0, "sellPrice": 416, "name": "Liquid Oxygen", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 120, "demand": 62211, "stockBracket": 0, "sellPrice": 213, "name": "Water", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 285, "demand": 1, "stockBracket": 2, "sellPrice": 151, "name": "Clothing", "stock": 51836, "buyPrice": 163, "demandBracket": 0}, {"meanPrice": 6769, "demand": 236, "stockBracket": 0, "sellPrice": 6561, "name": "Consumer Technology", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 487, "demand": 1, "stockBracket": 2, "sellPrice": 310, "name": "Domestic Appliances", "stock": 31071, "buyPrice": 326, "demandBracket": 0}, {"meanPrice": 485, "demand": 1, "stockBracket": 3, "sellPrice": 521, "name": "Survival Equipment", "stock": 2801, "buyPrice": 548, "demandBracket": 0}, {"meanPrice": 137, "demand": 61091, "stockBracket": 0, "sellPrice": 194, "name": "Algae", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 1292, "demand": 7003, "stockBracket": 0, "sellPrice": 1637, "name": "Animalmeat", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 1279, "demand": 230, "stockBracket": 0, "sellPrice": 1286, "name": "Coffee", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 406, "demand": 11041, "stockBracket": 0, "sellPrice": 422, "name": "Fish", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 105, "demand": 1, "stockBracket": 2, "sellPrice": 24, "name": "Food Cartridges", "stock": 26565, "buyPrice": 31, "demandBracket": 0}, {"meanPrice": 312, "demand": 833, "stockBracket": 0, "sellPrice": 315, "name": "Fruit And Vegetables", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 210, "demand": 19657, "stockBracket": 0, "sellPrice": 207, "name": "Grain", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 271, "demand": 541, "stockBracket": 0, "sellPrice": 252, "name": "Synthetic Meat", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 1467, "demand": 314, "stockBracket": 0, "sellPrice": 1459, "name": "Tea", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 3132, "demand": 37384, "stockBracket": 0, "sellPrice": 6741, "name": "C M M Composite", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 232, "demand": 589002, "stockBracket": 0, "sellPrice": 391, "name": "Ceramic Composites", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 403, "demand": 127104, "stockBracket": 0, "sellPrice": 1661, "name": "Cooling Hoses", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 7837, "demand": 23389, "stockBracket": 0, "sellPrice": 11695, "name": "Insulating Membrane", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 171, "demand": 566738, "stockBracket": 0, "sellPrice": 248, "name": "Polymers", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 967, "demand": 763461, "stockBracket": 0, "sellPrice": 1328, "name": "Semiconductors", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 6609, "demand": 2969, "stockBracket": 0, "sellPrice": 6561, "name": "Superconductors", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 357, "demand": 1, "stockBracket": 2, "sellPrice": 211, "name": "Atmospheric Extractors", "stock": 39916, "buyPrice": 227, "demandBracket": 0}, {"meanPrice": 980, "demand": 1, "stockBracket": 3, "sellPrice": 670, "name": "Building Fabricators", "stock": 8676, "buyPrice": 691, "demandBracket": 0}, {"meanPrice": 2021, "demand": 1, "stockBracket": 2, "sellPrice": 1852, "name": "Crop Harvesters", "stock": 28200, "buyPrice": 1908, "demandBracket": 0}, {"meanPrice": 1011, "demand": 14923, "stockBracket": 0, "sellPrice": 2756, "name": "Emergency Power Cells", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 479, "demand": 18191, "stockBracket": 0, "sellPrice": 2191, "name": "Exhaust Manifold", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 1661, "demand": 1, "stockBracket": 3, "sellPrice": 1221, "name": "Geological Equipment", "stock": 297228, "buyPrice": 1259, "demandBracket": 0}, {"meanPrice": 406, "demand": 1, "stockBracket": 3, "sellPrice": 1292, "name": "H N Shock Mount", "stock": 35950, "buyPrice": 1332, "demandBracket": 0}, {"meanPrice": 3916, "demand": 1, "stockBracket": 3, "sellPrice": 3329, "name": "Marine Supplies", "stock": 248426, "buyPrice": 3386, "demandBracket": 0}, {"meanPrice": 443, "demand": 1, "stockBracket": 2, "sellPrice": 423, "name": "Mineral Extractors", "stock": 83886, "buyPrice": 445, "demandBracket": 0}, {"meanPrice": 458, "demand": 1, "stockBracket": 3, "sellPrice": 221, "name": "Power Generators", "stock": 268499, "buyPrice": 232, "demandBracket": 0}, {"meanPrice": 859, "demand": 1, "stockBracket": 3, "sellPrice": 509, "name": "Skimer Components", "stock": 6669, "buyPrice": 525, "demandBracket": 0}, {"meanPrice": 256, "demand": 1, "stockBracket": 3, "sellPrice": 109, "name": "Thermal Cooling Units", "stock": 28884, "buyPrice": 117, "demandBracket": 0}, {"meanPrice": 258, "demand": 1, "stockBracket": 2, "sellPrice": 141, "name": "Water Purifiers", "stock": 16165, "buyPrice": 152, "demandBracket": 0}, {"meanPrice": 1259, "demand": 11781, "stockBracket": 0, "sellPrice": 2820, "name": "Advanced Medicines", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 279, "demand": 1, "stockBracket": 2, "sellPrice": 160, "name": "Basic Medicines", "stock": 11119, "buyPrice": 173, "demandBracket": 0}, {"meanPrice": 6816, "demand": 81, "stockBracket": 0, "sellPrice": 6561, "name": "Performance Enhancers", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 6779, "demand": 64, "stockBracket": 0, "sellPrice": 6561, "name": "Progenitor Cells", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 340, "demand": 136853, "stockBracket": 0, "sellPrice": 353, "name": "Aluminium", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 8288, "demand": 28736, "stockBracket": 0, "sellPrice": 8758, "name": "Beryllium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 647, "demand": 3491, "stockBracket": 0, "sellPrice": 701, "name": "Cobalt", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 481, "demand": 339151, "stockBracket": 0, "sellPrice": 550, "name": "Copper", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 5135, "demand": 204129, "stockBracket": 0, "sellPrice": 5532, "name": "Gallium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 9401, "demand": 122783, "stockBracket": 0, "sellPrice": 10145, "name": "Gold", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 5727, "demand": 1677, "stockBracket": 0, "sellPrice": 5743, "name": "Indium", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 1596, "demand": 186572, "stockBracket": 0, "sellPrice": 1881, "name": "Lithium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 7591, "demand": 143926, "stockBracket": 0, "sellPrice": 11910, "name": "Osmium", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 13298, "demand": 99967, "stockBracket": 0, "sellPrice": 13994, "name": "Palladium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 19279, "demand": 7478, "stockBracket": 0, "sellPrice": 23714, "name": "Platinum", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 7156, "demand": 75390, "stockBracket": 0, "sellPrice": 8613, "name": "Praseodymium", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 6330, "demand": 79751, "stockBracket": 0, "sellPrice": 8100, "name": "Samarium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 4775, "demand": 18504, "stockBracket": 0, "sellPrice": 5080, "name": "Silver", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 3962, "demand": 329125, "stockBracket": 0, "sellPrice": 4545, "name": "Tantalum", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 1006, "demand": 5120, "stockBracket": 0, "sellPrice": 1004, "name": "Titanium", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 2705, "demand": 448314, "stockBracket": 0, "sellPrice": 3170, "name": "Uranium", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 57445, "demand": 3740, "stockBracket": 0, "sellPrice": 69301, "name": "Low Temperature Diamond", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 40508, "demand": 780, "stockBracket": 0, "sellPrice": 75047, "name": "Painite", "stock": 0, "buyPrice": 0, "demandBracket": 3}, {"meanPrice": 186, "demand": 78596, "stockBracket": 0, "sellPrice": 316, "name": "Beer", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 587, "demand": 1, "stockBracket": 2, "sellPrice": 383, "name": "Liquor", "stock": 1485, "buyPrice": 402, "demandBracket": 0}, {"meanPrice": 260, "demand": 17975, "stockBracket": 0, "sellPrice": 349, "name": "Wine", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"stockBracket": 0, "demand": 52307, "buyPrice": 0, "statusFlags": ["powerplay"], "sellPrice": 3940, "name": "Auto Fabricators", "stock": 0, "demandBracket": 2, "meanPrice": 3734}, {"stockBracket": 2, "demand": 1, "buyPrice": 417, "statusFlags": ["powerplay"], "sellPrice": 396, "name": "Computer Components", "stock": 3112, "demandBracket": 0, "meanPrice": 513}, {"stockBracket": 0, "demand": 612364, "buyPrice": 0, "statusFlags": ["powerplay"], "sellPrice": 464, "name": "Hazardous Environment Suits", "stock": 0, "demandBracket": 3, "meanPrice": 340}, {"meanPrice": 3274, "demand": 2821, "stockBracket": 0, "sellPrice": 5373, "name": "Micro Controllers", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"stockBracket": 0, "demand": 82780, "buyPrice": 0, "statusFlags": ["powerplay"], "sellPrice": 2256, "name": "Robotics", "stock": 0, "demandBracket": 2, "meanPrice": 1856}, {"meanPrice": 507, "demand": 68131, "stockBracket": 0, "sellPrice": 1092, "name": "Conductive Fabrics", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 205, "demand": 693487, "stockBracket": 0, "sellPrice": 367, "name": "Leather", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 439, "demand": 249617, "stockBracket": 0, "sellPrice": 659, "name": "Natural Fabrics", "stock": 0, "buyPrice": 0, "demandBracket": 2}, {"meanPrice": 211, "demand": 132801, "stockBracket": 0, "sellPrice": 196, "name": "Synthetic Fabrics", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 63, "demand": 1, "stockBracket": 2, "sellPrice": 7, "name": "Biowaste", "stock": 13455, "buyPrice": 10, "demandBracket": 0}, {"meanPrice": 48, "demand": 1, "stockBracket": 3, "sellPrice": 18, "name": "Scrap", "stock": 151365, "buyPrice": 21, "demandBracket": 0}, {"meanPrice": 1837, "demand": 314, "stockBracket": 0, "sellPrice": 1766, "name": "Non Lethal Weapons", "stock": 0, "buyPrice": 0, "demandBracket": 1}, {"meanPrice": 2113, "demand": 241, "stockBracket": 0, "sellPrice": 2008, "name": "Reactive Armour", "stock": 0, "buyPrice": 0, "demandBracket": 1}], "systemName": "LP 356-106", "timestamp": "2017-09-10T12:43:23Z", "stationName": "Carrier Dock"}}'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eddnlistener.py", line 175, in <module>
    main()
  File "./eddnlistener.py", line 142, in main
    __db.insertMessage(__eddn_message.json, __eddn_message.schemaref, __eddn_message.gatewaytimestamp,__message_blacklisted, __message_valid, __message_schema_is_test)
  File "/mnt/tuesday/data0/edda/edda.git/eddn-listener/eddn/database/database.py", line 37, in insertMessage
    except sqlalchemy.exc.OperationalError as ex:
NameError: name 'sqlalchemy' is not defined
You have mail in /home/users/athan/Maildir
athan@tuesday:/mnt/tuesday/data0/edda/edda.git/eddn-listener;
13:43:19 0$

When this happens, as admin user:
VACUUM FULL messages;
e=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
